### ISSUE TITLE
Finding Inspiration

### ISSUE THREAD

**Issue by ijxsid** [joyeecheung/my-tech-diary#2]
First, this is not a tech issue, I am just wondering how you were able to write in this journal for so long without losing motivation. Like How you maintain this spree, is there a particular time you choose to write all about the day once or you keep the text editor open and write stuff as you go? 

I have been pretty inconsistent in last few years, and I see this as a really consistent effort of yours. So I just want to know how you're able to keep up.

**Comment by joyeecheung** [comment]
In case you didn't notice, the tool I wrote to generate a static site for this(https://github.com/joyeecheung/diary) can't generate a calendar index skipping even one day. This is intentional, so I can force myself to write diary everyday to avoid 404 in my site(triggering my inner OCD here, ;)).

I usually write the diary after work, sometime between 8:00PM ~ 1:00 AM the next day. I don't bring my laptop everywhere, it's left in my apartment, but the text editor is always open. Once I go back home from work, I start writing. But I don't always commit or deploy to the site after finishing one piece. Once you turn it into a habit, it's pretty easy to keep up.

**Comment by ijxsid** [comment]
Cool. I started doing somewhat the same thing. But mostly I am using a simple Markdown Editor with dropbox for syncing. Dropbox does provide some version control, which is nice. might shift to git afterwards. Dropbox keeps syncing Even if I forget to commit/push, which is good for me since I often forget doing that(ADHD). I have to keep doing things, otherwise I forget and get lazy. 

Also I thought of using pytumblr to keep syncing with some private tumblr blog, so I can see things in more pleasant way if I want to.

Thanks BTW for your inspiration.

**Comment by joyeecheung** [comment]
Glad to help :)
